packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/zod
  - packages/valibot
  - packages/nuxt
  - packages/shared
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  vue: 3.5.13
  '@vue/reactivity': 3.5.13
  '@vue/runtime-core': 3.5.13
  '@vue/runtime-dom': 3.5.13
  '@vue/shared': 3.5.13
  '@vue/compiler-dom': 3.5.13
  '@vue/server-renderer': 3.5.13
  vue3.4: npm:vue@3.4.38
  '@vue/reactivity3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer3.4': npm:@vue/server-renderer@3.4.38
  pinia: 2.2.6
  pinia2.2.5: npm:pinia@2.2.5
  eslint: 9.15.0
  eslint-plugin-vue: 9.31.0
  eslint-config-prettier: 9.1.0
  vue-eslint-parser: 9.4.3
  type-fest: 4.28.0
  prettier: 3.3.3
  typescript: 5.6.3
  vue-tsc: 2.1.10
  tsup: 8.3.5
