packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/shared
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  '@types/node': 22.18.0
  # Vue
  vue: 3.5.21
  '@vue/reactivity': 3.5.21
  '@vue/runtime-core': 3.5.21
  '@vue/runtime-dom': 3.5.21
  '@vue/shared': 3.5.21
  '@vue/compiler-dom': 3.5.21
  '@vue/server-renderer': 3.5.21

  # Vue 3.4
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38

  # Vue Ecosystem
  '@vue/test-utils': 2.4.6
  vue-router: 4.5.1
  vue-tsc: 3.0.6
  vue-eslint-parser: 10.2.0
  pinia: 3.0.3
  pinia-2.2.5: npm:pinia@2.2.5

  # Nuxt
  nuxt: 4.0.3
  '@nuxt/kit': 4.0.3
  '@nuxt/schema': 4.0.3

  # Devtools
  eslint: 9.34.0
  eslint-plugin-vue: 10.4.0
  eslint-config-prettier: 10.1.8
  expect-type: 1.2.2
  prettier: 3.6.2
  typescript: 5.9.2
  typescript-eslint: 8.42.0
  '@typescript-eslint/eslint-plugin': 8.42.0
  '@typescript-eslint/parser': 8.42.0
  '@total-typescript/ts-reset': 0.6.1
  tsdown: 0.14.2
  type-fest: 4.41.0

  # Vite
  vite: 7.1.4
  vitest: 3.2.4
  '@vitejs/plugin-vue': 6.0.1
  '@vitejs/plugin-vue-jsx': 5.1.1

  # Schemas libraries
  arktype: 2.1.20
  valibot: 1.1.0
  zod: 4.1.5
