packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/shared
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  vue: 3.5.13
  '@vue/reactivity': 3.5.13
  '@vue/runtime-core': 3.5.13
  '@vue/runtime-dom': 3.5.13
  '@vue/shared': 3.5.13
  '@vue/compiler-dom': 3.5.13
  '@vue/server-renderer': 3.5.13
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38
  pinia: 3.0.1
  pinia-2.2.5: npm:pinia@2.2.5
  eslint: 9.15.0
  eslint-plugin-vue: 9.31.0
  eslint-config-prettier: 9.1.0
  vue-eslint-parser: 9.4.3
  type-fest: 4.38.0
  prettier: 3.3.3
  nuxt: 3.16.1
  vue-router: 4.5.0
  # Nuxt buider not upgraded yet so TS should stay at 5.6.3
  typescript: 5.8.2
  vue-tsc: 2.2.8
  vitest: 3.1.1
  tsup: 8.4.0
  zod: 3.24.2
