packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/shared
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  '@types/node': 22.15.33
  # Vue
  vue: 3.5.17
  '@vue/reactivity': 3.5.17
  '@vue/runtime-core': 3.5.17
  '@vue/runtime-dom': 3.5.17
  '@vue/shared': 3.5.17
  '@vue/compiler-dom': 3.5.17
  '@vue/server-renderer': 3.5.17

  # Vue 3.4
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38

  # Vue Ecosystem
  '@vue/test-utils': 2.4.6
  vue-router: 4.5.1
  vue-tsc: 2.2.10
  vue-eslint-parser: 10.1.4
  pinia: 3.0.3
  pinia-2.2.5: npm:pinia@2.2.5

  # Nuxt
  nuxt: 3.17.5
  '@nuxt/kit': 3.17.5
  '@nuxt/schema': 3.17.5

  # Devtools
  eslint: 9.29.0
  eslint-plugin-vue: 10.2.0
  eslint-config-prettier: 10.1.5
  expect-type: 1.2.1
  prettier: 3.6.1
  typescript: 5.8.3
  typescript-eslint: 8.37.0
  '@typescript-eslint/eslint-plugin': 8.37.0
  '@typescript-eslint/parser': 8.37.0
  '@total-typescript/ts-reset': 0.6.1
  tsdown: 0.12.9
  type-fest: 4.41.0

  # Vite
  vite: 7.0.0
  vitest: 3.2.4

  # Schemas libraries
  arktype: 2.1.20
  valibot: 1.1.0
  zod: 3.25.67
