packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/zod
  - packages/valibot
  - packages/nuxt
  - packages/shared
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  vue: 3.5.13
  '@vue/reactivity': 3.5.13
  '@vue/runtime-core': 3.5.13
  '@vue/runtime-dom': 3.5.13
  '@vue/shared': 3.5.13
  pinia: 2.2.6
  eslint: 9.15.0
  eslint-plugin-vue: 9.31.0
  eslint-config-prettier: 9.1.0
  vue-eslint-parser: 9.4.3
  type-fest: 4.28.0
  prettier: 3.3.3
  typescript: 5.6.3
  vue-tsc: 2.1.10
  tsup: 8.3.5
