packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/shared
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

catalog:
  '@types/node': 22.15.3
  # Vue
  vue: 3.5.13
  '@vue/reactivity': 3.5.13
  '@vue/runtime-core': 3.5.13
  '@vue/runtime-dom': 3.5.13
  '@vue/shared': 3.5.13
  '@vue/compiler-dom': 3.5.13
  '@vue/server-renderer': 3.5.13
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38
  '@vue/test-utils': 2.4.6
  vue-router: 4.5.1
  vue-tsc: 2.2.10
  vue-eslint-parser: 10.1.3
  pinia: 3.0.2
  pinia-2.2.5: npm:pinia@2.2.5
  # Nuxt
  nuxt: 3.17.1
  '@nuxt/kit': 3.17.1
  '@nuxt/schema': 3.17.1
  # Devtools
  eslint: 9.25.1
  eslint-plugin-vue: 9.33.0
  eslint-config-prettier: 9.1.0
  expect-type: 1.2.1
  prettier: 3.5.3
  typescript: 5.8.3
  tsdown: 0.12.3
  type-fest: 4.40.1

  vite: 6.2.7
  vitest: 3.1.2
  # Schemas libraries
  arktype: 2.1.20
  valibot: 1.1.0
  zod: 3.25.30
