packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/shared
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - ui-tests/fixtures/ui-vue3

minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - tsdown
  - oxlint

catalog:
  '@types/node': 22.19.0
  # Vue
  vue: 3.5.22
  '@vue/reactivity': 3.5.22
  '@vue/runtime-core': 3.5.22
  '@vue/runtime-dom': 3.5.22
  '@vue/shared': 3.5.22
  '@vue/compiler-dom': 3.5.22
  '@vue/server-renderer': 3.5.22

  # Vue 3.4
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38

  # Vue Ecosystem
  '@vue/test-utils': 2.4.6
  vue-router: 4.6.3
  vue-tsc: 3.1.3
  vue-eslint-parser: 10.2.0
  pinia: 3.0.3
  pinia-2.2.5: npm:pinia@2.2.5

  # Nuxt
  nuxt: 4.1.2
  '@nuxt/kit': 4.1.2
  '@nuxt/schema': 4.1.2

  # Devtools
  expect-type: 1.2.2
  prettier: 3.6.2
  typescript: 5.9.3
  '@total-typescript/ts-reset': 0.6.1
  tsdown: 0.15.12
  type-fest: 5.2.0

  # Vite
  vite: 7.1.10
  vitest: 4.0.6
  '@vitejs/plugin-vue': 6.0.1
  '@vitejs/plugin-vue-jsx': 5.1.1

  # Schemas libraries
  arktype: 2.1.25
  valibot: 1.1.0
  zod: 4.1.12
