packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/nuxt/test/fixtures
  - packages/shared
  - packages/mcp-server
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - playground/advanced-example
  - ui-tests/fixtures/ui-vue3

minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - tsdown
  - oxlint
  - '@modelcontextprotocol/sdk'
  - lodash-es

catalog:
  '@types/node': 24.10.10
  # Vue
  vue: 3.5.27
  '@vue/reactivity': 3.5.27
  '@vue/runtime-core': 3.5.27
  '@vue/runtime-dom': 3.5.27
  '@vue/shared': 3.5.27
  '@vue/compiler-dom': 3.5.27
  '@vue/server-renderer': 3.5.27

  # Vue 3.4
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38

  # Vue Ecosystem
  vue-router: 5.0.2
  vue-tsc: 3.2.4
  vue-eslint-parser: 10.2.0
  pinia: 3.0.4
  pinia-2.2.5: npm:pinia@2.2.5

  # Nuxt
  nuxt: 4.3.0
  '@nuxt/kit': 4.3.0
  '@nuxt/schema': 4.3.0

  # Devtools
  typescript: 5.9.3
  '@total-typescript/ts-reset': 0.6.1
  tsdown: 0.20.1
  type-fest: 5.4.3
  'tsx': 4.21.0

  # Testing

  playwright: 1.58.1
  playwright-core: 1.58.1
  '@playwright/test': 1.58.1
  vitest: 4.0.18
  '@vue/test-utils': 2.4.6

  # Vite
  vite: 7.3.1
  '@vitejs/plugin-vue': 6.0.4
  '@vitejs/plugin-vue-jsx': 5.1.4

  # Schemas libraries
  arktype: 2.1.29
  valibot: 1.2.0
  zod: 4.3.6

  # Front
  tailwindcss: 4.1.18
  check-password-strength: 3.0.0
  sass: 1.97.3
