packages:
  - packages/core
  - packages/rules
  - packages/schemas
  - packages/nuxt
  - packages/nuxt/test/fixtures
  - packages/shared
  - packages/mcp-server
  - packages-private/regle-playground
  - tests
  - docs
  - playground/vue3
  - playground/nuxt
  - playground/advanced-example
  - ui-tests/fixtures/ui-vue3

minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - tsdown
  - oxlint

catalog:
  '@types/node': 22.19.1
  # Vue
  vue: 3.5.25
  '@vue/reactivity': 3.5.25
  '@vue/runtime-core': 3.5.25
  '@vue/runtime-dom': 3.5.25
  '@vue/shared': 3.5.25
  '@vue/compiler-dom': 3.5.25
  '@vue/server-renderer': 3.5.25

  # Vue 3.4
  vue-3.4: npm:vue@3.4.38
  '@vue/reactivity-3.4': npm:@vue/reactivity@3.4.38
  '@vue/runtime-core-3.4': npm:@vue/runtime-core@3.4.38
  '@vue/runtime-dom-3.4': npm:@vue/runtime-dom@3.4.38
  '@vue/shared-3.4': npm:@vue/shared@3.4.38
  '@vue/compiler-dom-3.4': npm:@vue/compiler-dom@3.4.38
  '@vue/server-renderer-3.4': npm:@vue/server-renderer@3.4.38

  # Vue Ecosystem
  vue-router: 4.6.3
  vue-tsc: 3.1.5
  vue-eslint-parser: 10.2.0
  pinia: 3.0.4
  pinia-2.2.5: npm:pinia@2.2.5

  # Nuxt
  nuxt: 4.2.1
  '@nuxt/kit': 4.2.1
  '@nuxt/schema': 4.2.1

  # Devtools
  prettier: 3.7.3
  typescript: 5.9.3
  '@total-typescript/ts-reset': 0.6.1
  tsdown: 0.16.8
  type-fest: 5.2.0
  'tsx': 4.21.0

  # Testing

  playwright: 1.56.1
  playwright-core: 1.56.1
  '@playwright/test': 1.56.1
  vitest: 4.0.13
  '@vue/test-utils': 2.4.6

  # Vite
  vite: 7.2.4
  '@vitejs/plugin-vue': 6.0.2
  '@vitejs/plugin-vue-jsx': 5.1.2

  # Schemas libraries
  arktype: 2.1.27
  valibot: 1.2.0
  zod: 4.1.13

  # Front
  tailwindcss: 4.1.17
  check-password-strength: 3.0.0
